spring.application.name=msvc-ram
server.port=8088

spring.datasource.url=jdbc:h2:mem:db_ram
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Usuario2
spring.datasource.password= Contrasena2!

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true