spring.application.name=msvc-component
server.port=8083
spring.datasource.url=jdbc:h2:mem:db_cpu
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Usuario1
spring.datasource.password=Contrasena1!
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Registro en Eureka. spring.application.name (arriba) es el nombre con que queda registrado.
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true